version: '3.9'

name: A_Square

services:
  image2sketch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: image2sketch
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8073:8073"
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
